# Generated by Django 5.0.6 on 2025-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
